// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ackley2D
double ackley2D(NumericVector x);
RcppExport SEXP _ballsdKHCpp_ackley2D(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ackley2D(x));
    return rcpp_result_gen;
END_RCPP
}
// griewank2D
double griewank2D(Rcpp::NumericVector x);
RcppExport SEXP _ballsdKHCpp_griewank2D(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(griewank2D(x));
    return rcpp_result_gen;
END_RCPP
}
// ackley2D
double ackley2D(NumericVector x);
RcppExport SEXP _ballsdKHCpp_ackley2D(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ackley2D(x));
    return rcpp_result_gen;
END_RCPP
}
// griewank2D
double griewank2D(Rcpp::NumericVector x);
RcppExport SEXP _ballsdKHCpp_griewank2D(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(griewank2D(x));
    return rcpp_result_gen;
END_RCPP
}
// ballsd
NumericVector ballsd(NumericVector x0, Function objFunc, double sinc, double sdec, double pinc, double pdec, int maxIter);
RcppExport SEXP _ballsdKHCpp_ballsd(SEXP x0SEXP, SEXP objFuncSEXP, SEXP sincSEXP, SEXP sdecSEXP, SEXP pincSEXP, SEXP pdecSEXP, SEXP maxIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< Function >::type objFunc(objFuncSEXP);
    Rcpp::traits::input_parameter< double >::type sinc(sincSEXP);
    Rcpp::traits::input_parameter< double >::type sdec(sdecSEXP);
    Rcpp::traits::input_parameter< double >::type pinc(pincSEXP);
    Rcpp::traits::input_parameter< double >::type pdec(pdecSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    rcpp_result_gen = Rcpp::wrap(ballsd(x0, objFunc, sinc, sdec, pinc, pdec, maxIter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ballsdKHCpp_ackley2D", (DL_FUNC) &_ballsdKHCpp_ackley2D, 1},
    {"_ballsdKHCpp_griewank2D", (DL_FUNC) &_ballsdKHCpp_griewank2D, 1},
    {"_ballsdKHCpp_ackley2D", (DL_FUNC) &_ballsdKHCpp_ackley2D, 1},
    {"_ballsdKHCpp_griewank2D", (DL_FUNC) &_ballsdKHCpp_griewank2D, 1},
    {"_ballsdKHCpp_ballsd", (DL_FUNC) &_ballsdKHCpp_ballsd, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ballsdKHCpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
