# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ackley's function in 2D
NULL

ackley2D <- function(x) {
    .Call('_ballsdKHCppHW2_ackley2D', PACKAGE = 'ballsdKHCppHW2', x)
}

griewank2D <- function(x) {
    .Call('_ballsdKHCppHW2_griewank2D', PACKAGE = 'ballsdKHCppHW2', x)
}

#' Ball's Algorithm for Stochastic Descent (ballsd)
NULL

ballsd <- function(x0, objFunc, sinc, sdec, pinc, pdec, maxIter) {
    .Call('_ballsdKHCppHW2_ballsd', PACKAGE = 'ballsdKHCppHW2', x0, objFunc, sinc, sdec, pinc, pdec, maxIter)
}

