# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ackley2D <- function(x) {
    .Call(`_ballsdKHCpp_ackley2D`, x)
}

griewank2D <- function(x) {
    .Call(`_ballsdKHCpp_griewank2D`, x)
}

ackley2D <- function(x) {
    .Call(`_ballsdKHCpp_ackley2D`, x)
}

griewank2D <- function(x) {
    .Call(`_ballsdKHCpp_griewank2D`, x)
}

ballsd <- function(x0, objFunc, sinc, sdec, pinc, pdec, maxIter) {
    .Call(`_ballsdKHCpp_ballsd`, x0, objFunc, sinc, sdec, pinc, pdec, maxIter)
}

